#!/usr/bin/env python3
"""
Fetch Medium RSS feed and write _data/medium_posts.yml.

Usage:
    python3 scripts/fetch_medium.py

The script tries each feed URL in order and uses the first that responds.
Output is written to _data/medium_posts.yml (relative to repo root).
"""
import os
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from email.utils import parsedate_to_datetime

FEED_URLS = [
    "https://medium.com/feed/@leonardobbai",
    "https://leonardobbai.medium.com/feed",
]

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT  = os.path.dirname(SCRIPT_DIR)
OUTPUT     = os.path.join(REPO_ROOT, "_data", "medium_posts.yml")


def fetch(url: str) -> bytes:
    req = urllib.request.Request(
        url,
        headers={"User-Agent": "Mozilla/5.0 (compatible; portfolio-sync/1.0)"},
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        return resp.read()


def strip_html(html: str) -> str:
    text = re.sub(r"<[^>]+>", " ", html)
    text = re.sub(r"&[a-z]+;", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return (text[:280] + "…") if len(text) > 280 else text


def parse(data: bytes) -> list[dict]:
    ns = {"content": "http://purl.org/rss/1.0/modules/content/"}
    root = ET.fromstring(data)
    posts = []
    for item in root.findall(".//item"):
        title = (item.findtext("title") or "").strip()
        link  = (item.findtext("link")  or "").strip()
        if not title or not link:
            continue

        pub_date_str = item.findtext("pubDate") or ""
        try:
            date = parsedate_to_datetime(pub_date_str).strftime("%Y-%m-%d")
        except Exception:
            date = ""

        raw = (
            item.findtext("content:encoded", namespaces=ns)
            or item.findtext("description")
            or ""
        )
        excerpt = strip_html(raw)
        posts.append({"title": title, "url": link, "date": date, "excerpt": excerpt})
    return posts


def escape_yaml_str(s: str) -> str:
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def render_yaml(posts: list[dict]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Generated by scripts/fetch_medium.py — do not edit manually.",
        f"# Last updated: {now}",
        "posts:",
    ]
    for p in posts:
        lines += [
            f"  - title:   {escape_yaml_str(p['title'])}",
            f"    url:     {escape_yaml_str(p['url'])}",
            f"    date:    {escape_yaml_str(p['date'])}",
            f"    excerpt: {escape_yaml_str(p['excerpt'])}",
        ]
    return "\n".join(lines) + "\n"


def main() -> None:
    data = None
    for url in FEED_URLS:
        try:
            print(f"Trying {url} …", flush=True)
            data = fetch(url)
            print(f"  OK — {len(data)} bytes", flush=True)
            break
        except Exception as exc:
            print(f"  Failed: {exc}", file=sys.stderr)

    if data is None:
        print("Error: all feed URLs failed.", file=sys.stderr)
        sys.exit(1)

    posts = parse(data)
    print(f"Parsed {len(posts)} posts.", flush=True)

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as fh:
        fh.write(render_yaml(posts))
    print(f"Written → {OUTPUT}", flush=True)


if __name__ == "__main__":
    main()
